### PR TITLE
Added smearing for photon energy

### PR DESCRIPTION
**Pull request by gcowan**
Added a new class for smearing of photon energy, inheriting from the standard RapidMomentumSmear class.
Added an LHCbPhoton smear config file, with parameters for the stochastic and constant terms of he resolution taken from the ECAL TDR.
Added a new .decay and .config file that uses the LHCbPhoton.

### CODE REVIEW

**Comment by particleist** [comment]
It's automatic that photons will not get any variables filled which aren't relevant for them?

**Comment by gcowan** [comment]
At the moment, to keep things simple photons are just treated like any other stable particle.

**Comment by particleist** [comment]
OK fair enough, I guess theorists will not start using photon impact parameters...

**Comment by gcowan** [comment]
For the PID I have a check in RapidParam::evalPID() such that the PID information is only filled if the particle has mass > 0. Could do something similar in RapidParam::eval() for the IP information.

**Comment by particleist** [comment]
But the code in evalPID will still leave the branch there in the ntuple, no?

**Comment by gcowan** [comment]
Yes. A bit untidy, but keeps things simple (maybe the user won't think that...)

**Comment by particleist** [comment]
Yeah I don't think the user will think that TBH...

**Comment by gcowan** [comment]
You think they will just get confused?

**Comment by particleist** [comment]
I think the potential is there, yeah. Maybe not a huge potential but I would have thought having a paramsNeutral would be (while a bit more work to implement) helpful in the long run, especially once we start adding brems.

**Comment by gcowan** [comment]
We probably need to think a bit before implementing paramsNeutral (actually, probably better to be paramsStableAndNeutral). Somewhere like RapidConfig::setupDefaultParams() would then have to have the logic to know which parameters are allowed and which are not. I guess this is doable (we already have some logic for checking of the (COS)THETA parameter is defined with two particles or not) but I worry about corner cases that we forget about and/or make the configuration overly restrictive such that we then forbid a new use case.

**Pull request merged**
