### PR TITLE
Impactparameters

### PR DESCRIPTION
**Pull request by particleist**
This should be enough to handle pileup. There is some very nasty coding in RapidDecay to pick the MinIP based on the smeared and not true IP, but I couldn't find a better way because a particle owns its own IP smearing class. I would appreciate it if someone could check the units in beams, I am trying to set a 6cm beamspot in Z and 35 microns in X and Y.

### CODE REVIEW

**Comment by particleist** [comment]
Note that I have also added saving of true FD info, fixed a bug to make sure parameters can be either smeared, true, or both, and also modified the logic of the IP smearing. The sigma which it returns is now the actual sigma thrown by the RNG.

**Comment by dcraik** [comment]
Branch is currently failing to build in CI: https://gitlab.cern.ch/dcraik/RapidSim2/pipelines/250172

Looks like it's just an unused variable.

/builds/dcraik/RapidSim2/src/RapidDecay.cc:250:19: error: variable 'minip' set but not used [-Werror=unused-but-set-variable]

**Comment by particleist** [comment]
Better now?

**Comment by particleist** [comment]
I'm not sure I really understand what this is testing?

**Comment by dcraik** [comment]
Sorry posted too soon. The tests check that the histograms produced by the validation modes remain statistically consistent after each commit so, if anything changes legitimately, we need to update the files in validation/rootfiles

In B2Kee, it looks like the parameter K_SIGMAIP no longer exists - from the code, I guess it might be called K_SIGMAIP_TRUE now?

The other histograms up to that point have reasonable p-values so it's probably just a case of replacing the validation histogram with one that has the correct variable name (and also has MINIP).

I've got the validation script handy so I'll try updating the file now.

**Comment by particleist** [comment]
Yes, SIGMAIP is now correctly a truth level only variable. Thanks Dan!

**Comment by dcraik** [comment]
Looks OK to merge now.

The indentation looks odd (github displays tabs as eight spaces and I guess your editor is converting tabs to four spaces?) but I'll do a "gg=G" pass later.

Will open an issue on the cached IP hack.

**Pull request merged**
