### PR TITLE
Clean version of Vava's code for brem modeling

### PR DESCRIPTION
**Pull request by vlisovsk**

### CODE REVIEW

**Comment by vlisovsk** [comment]
You are right, something went wrong when commiting the changes.
I would prefer if @particleist can confirm, but the files relevant to the brem studies are velo.cc/h, fastsim.cc/h, and also RapidMomentumSmearBrems, right?
So then I create a new branch based on master with only these 6 files added?

**Comment by particleist** [comment]
Yeah, those are the relevant files (also the B2Kee file in validation, and you need the relevant smearing file for Brems in config). Indeed suggest you

a) Make a new branch off master

b) Update the relevant files in it

c) Commit and push to that branch so Greig & Dan can test and play with it

**Comment by vlisovsk** [comment]
You mean the branch with just relevant files and nothing else?

**Comment by particleist** [comment]
No sorry, let me be clearer. You start with master and branch off it, so you have a copy of RapidSim in this branch. You then add the relevant bits for the Brems, and commit and then push to this branch (not to master). Then we can all work and test these additions from that branch, without touching master.

**Comment by vlisovsk** [comment]
Then it is exactly what I was intended to do. Thanks for the clarifications!

**Comment by vlisovsk** [comment]
Now it should be OK.

**Pull request closed without merging**
